### ISSUE TITLE
Shape graphics not behaving as expected

### ISSUE THREAD

**Issue by cherreman** [bp74/StageXL#16]
As a small test, I created a Shape, drew a circle in it and added an enter_frame handler to move the shape. In ActionScript this results in the circle moving across the screen. In StageXL however, the shape is always redrawn and overlaps with what was drawn the previous frames.

Example in ActionScript:

```
var ball:Shape = new Shape();
ball.graphics.beginFill(0xFF9900);
ball.graphics.drawCircle(100, 100, 25);
ball.graphics.endFill();
addChild(ball);

addEventListener(Event.ENTER_FRAME, function (event:Event):void {
    ball.x++;
});
```

Example in Dart:

```
var ball = new Shape();
ball.graphics.fillColor(0xFFFF9900);
ball.graphics.circle(100, 100, 25);
stage.addChild(ball);

stage.addEventListener(Event.ENTER_FRAME, (event){
    ball.x++;
});
```

**Comment by shankarthapa** [comment]
I am new bie to Dartjs, not sure where to post.
But found this post in google search. So posting my query here only.

I am little confused regarding fillColor parameter
its "fillColor(0xFFFF9900)". 
its 8 Digits :- 0xFFFF9900
where as in AS or in CSS, it use to be 6 Digit.
I see 00 extra, do i have add 00 to every color property ?
If not than, is there any color picker type tool with that i can pick 8 Digit color code.

**Comment by bp74** [comment]
The color in StageXL is a 32 bit integer (like it is in Flash) for ARGB (Alpha, Red, Green, Blue).
Example: 0xFF506070 => Alpha = 0xFF, Red = 0xF=, Green = 0x60, Blue = 0x70

You can also use the Color class which gives you predefined colors.
https://github.com/bp74/StageXL/blob/master/lib/src/ui/color.dart

Hope this helps!

**Comment by shankarthapa** [comment]
many thanks for clearing me
:+1:
