### ISSUE TITLE
IOS 8 webGl issues

### ISSUE THREAD

**Issue by khuram99** [bp74/StageXL#160]
Hi,

I'm having an issue on IOS -8. Ios 8 has webGl enabled and when I use WebGl mode in StageXl it has some issues. EVery time we render something to stage, a Big black box flickers for a sec and goes away. It only  happens if I use Stagexl with webGl, if I use WebGl = false it works fine as it uses canvas mode.

Any immediate help will be great as we are near to our demo with Dart and StageXl as a tech choice for building games.

**Comment by overdub** [comment]
I can confirm the issue - in my case it only happens with textfields. Sometimes just a flickering black box, sometimes a solid black texture over the entire Textfield. 
Is this maybe related to transparent texture generation?

**Comment by bp74** [comment]
Do you update this TextField frequently? Maybe the texture upload to WebGL is delayed for some strange reason. If the black box appears after an update of the TextField and the black boy disappears if the TextField isn't updated it would make sense. Then we could check why the WebGL texture upload is delayed.

**Comment by bp74** [comment]
In issue #87 (which isn't really related to this problem) we have found the solution for the flickering. It's the texture slot we are using to upload the texture which is not supported in iOS. iOS only supports only 8 slots but we were using slot 10 - very very bad.

I will fix the code and do some other cleanups over the next few days.

**Comment by bp74** [comment]
Fixed in StageXL 0.12
