### ISSUE TITLE
Scaling Issue on Retina screens

### ISSUE THREAD

**Issue by khuram99** [bp74/StageXL#161]
Hi!

We’ve implemented a canvas and stage suitable for retina (Macbook) and regular display as well, and we’ve got a problem with resizing browser window. The implementation is as follows:

    CanvasElement canvas = querySelector('#stage');
    canvas.width = window.innerWidth;
    canvas.height = window.innerHeight;

    window.onResize.listen((value) {
      canvas.width = window.innerWidth;
      canvas.height = window.innerHeight;
    });

    stage = new Stage(canvas, webGL:false, width:window.innerWidth, height:window.innerHeight);

What we need is, that our content should remain the same, centered, and we’ll handle redrawing the edges. So I added the following lines:

    stage.scaleMode = StageScaleMode.NO_SCALE;
    stage.align = StageAlign.TOP_LEFT;

And this works like charm on normal displays, however, on retina, due to the resetting of stage’s scales to 1, its falling apart. 
Since I can’t set stage’s scale props, I’d either need a StageScaleMode.NO_CHANGE, or StageScaleMode.RETINA to fix this issue.
Am I correct, or did I miss something?

Cheers,
Gabor and Khuram

**Comment by bp74** [comment]
I will close this issue since there isn't much we can do right now. Please reply if there is anything StageXL should change when it comes the the Stage scaling stuff.
