### ISSUE TITLE
DisplayObject: Graphics ignored by width and height getters

### ISSUE THREAD

**Issue by nilsdoehring** [bp74/StageXL#172]
Hi Bernhard,

between 10.1 and 10.2 (github) DisplayObject started ignoring width and height of contained Graphics.
The test below prints 0.0 for both. 
```
  Sprite s = new Sprite();
  s.graphics.rect(0, 0, 100, 100);
  s.graphics.fillColor(0xFFFF0000);
  
  stage.addChild(s);
  
  print("width: ${s.width}");
  print("height: ${s.height}");
```

Probably related: It is not possible to resize contained Graphics via width and height setters, anymore.
i.e. setting 
    s.height = 200; 
produces no result (should output a red square with 200px height).

Both was working in 10.1

**Comment by bp74** [comment]
Sorry for this issue and I will correct it asap! Thanks for the report

**Comment by bp74** [comment]
I have fixed this issue in the master branch. I will release a new version to Pub soon to make this fix available for everyone.

**Comment by nilsdoehring** [comment]
everything back to normal. 
perfect, thanks!
