### ISSUE TITLE
BitmapData from TextField

### ISSUE THREAD

**Issue by ViliX64** [bp74/StageXL#182]
I'm using lots of TextFields in my game and that leads to performance issues. The TextFields contain usually only one character that doesn't change (as well as the TextFormat that changes very rarely). I was thinking if there's a way of **getting Bitmap out of the TextField** and using that instead of the TextField itself (rendering text is quite slow).

I'm sorry if this is a newbie question, but I'm stuck on this issue for a while.

**Comment by bp74** [comment]
Hi,

Thanks for the question. Yes you can do this. The TextField is a DisplayObject like any other, and the BitmapData object has a draw method. With this draw method you can draw any DisplayObject to the BitmapData.

The TextField has a built in cache which renderes the Text to a Texture (kind of a low level BitmapData) which is enabled by default. You can enable and disable this cache by setting the cacheAsBitmap property.

If you are using the WebGL renderer you would get much better performance if you draw all the TextFields to a common BitmapData (Texture). Take a look at the BitmapDataUpdateBatch class if you do many draws to the BitmapData. Let's say you use a 512x512 Pixel BitmapData for all your texts, then you can use the BitmapData.fromBitmapData(..) constructor to create sub-BitmapDatas for your texts. Those sub BitmapDatas look like independed BitmapDatas, but in fact they all share the same texture internally. This makes it very fast in WebGL.

Hope this helps and answers your question

**Comment by bp74** [comment]
Forgot to say one more thing: If you draw the TextFields to a BitmapData, you should set cacheAsBitmap to false. Otherwise you would use the cache of the TextField and your BitmapData.

**Comment by ViliX64** [comment]
I think it did. Thanks for your answer.
