### ISSUE TITLE
Problem in running project

### ISSUE THREAD

**Issue by KakashiSensei** [bp74/StageXL#185]
Hi,

I am trying to run a old project but dart editor is giving error
Unable to get content: FileSystemException: Failed to decode data using encoding 'utf-8'
and nothing is loading in dartium

**Comment by bp74** [comment]
Very strange. Do you think this is related to StageXL ?

**Comment by KakashiSensei** [comment]
No I don't think so its related with StageXL. Making new project doesn't show this problem. Is the problem related with packages can I clean the packages and download them again?

**Comment by bp74** [comment]
Yes you can try "Pub get" or "Pub upgrade" by right-clicking on "pubspec.yaml".
If this does not work you can call "Pub cache repair" on the command line.

https://www.dartlang.org/tools/pub/cmd/pub-cache.html

**Comment by KakashiSensei** [comment]
This is the error I am getting right now 

i18n-values: Missing value for "primaryParagraph" (data:text/html,chromewebdata:3183)
Failed to load resource: net::ERR_NAME_NOT_RESOLVED

do you have any idea about this?

**Comment by bp74** [comment]
Unofortunately i don't know the answer or have a clue what this could mean. I think it would be best to ask this question on StackOverflow since this has nothing to do with StageXL. Here is a link to StackOverflow with the Dart tag:

http://stackoverflow.com/questions/ask?tags=dart
