### ISSUE TITLE
TouchEnd is fired when finger is not removed from screen

### ISSUE THREAD

**Issue by KakashiSensei** [bp74/StageXL#191]
I am trying to make pinch gesture from the touch points. But when I bring the two touch point closer to the each other, it fires TOUCH_END and and TOUCH_BEGIN again even when both of the fingers are on the screen. This does not happen when both the touch point are away.

**Comment by bp74** [comment]
Hi, 

Yes i know this problem but it is not related to StageXL. The touch is triggered by the underlying browser and/or hardware, and it's the browser who controls when a touch starts and ends. Below is a link to a simple test example i'm using to do tests with touch events - if you bring the fingers very close to each other you can see that one touch event ends and sometimes a new one is started. I'm not sure if it is more related to the hardware or the browser who decides when a touch is started or ended.

http://www.stagexl.org/temp/example11/example11.html
