### ISSUE TITLE
Soft Keyboard for textField of type input

### ISSUE THREAD

**Issue by KakashiSensei** [bp74/StageXL#192]
I am trying to get the soft keyboard for input textfield using
stage.focus = textfield;

I do get the cursor but no soft keyboard.

How to get the soft keyboard?

Thanks

**Comment by bp74** [comment]
Hi,

Do you mean the on screen keyboard of mobile phones? Unfortunately this is not possible :( There is no API we could use to activate the keyboard and use it for the TextField. The only workaround you could use is to add a "HtmlObject" display object on top of the Stage. You could add add standard html input element which will activate the keyboard.

http://www.stagexl.org/docs/api/index.html#stagexl/stagexl-display_ex.HtmlObject@id_HtmlObject-

Hope this helps,
Bernhard
