### ISSUE TITLE
Scale9Bitmap issue in 0.12.0 dev version

### ISSUE THREAD

**Issue by KakashiSensei** [bp74/StageXL#193]
I am getting this issue
type 'double' is not a subtype of type 'int' of 'value'

My bitmapWidth is 26 but it is taken as 26.0 and in ensureInt, it shows error.

I have to use dev version for bitmap font.

**Comment by bp74** [comment]
Thanks for the bug report. I confirm that this is an issue and I will fix it later today. Sorry for any inconveniences.

**Comment by bp74** [comment]
The bug should be fixed now, it would be great if you could give it a try. Thanks for the bug report.

**Comment by KakashiSensei** [comment]
Yes the bug is fixed. Thanks for quick response.
