### ISSUE TITLE
Alpha not working on bitmap with tint filter

### ISSUE THREAD

**Issue by KakashiSensei** [bp74/StageXL#194]
I am trying to change the alpha of Bitmap on which tint filter is applied. It seems that with tint filter on bitmap no alpha property on bitmap is applied. I am using tint filter to apply color on bitmap font and want to change the alpha. I am using the dev version (0.12.0). I haven't checked in previous version.

Thanks

**Comment by bp74** [comment]
Thanks for the bug report. I can see what the problem is. It is the pre-multiplied alpha thing with the tint color. It's an easy fix and I will commit the changes a little but later today.

**Comment by bp74** [comment]
I fixed the issue with the TintFilter. Please do a quick test to see if it works as exepected. I did some tests too and i think it's correct now.

**Comment by bp74** [comment]
Fixed in StageXL 0.12
