### ISSUE TITLE
Scale9Bitmap not working

### ISSUE THREAD

**Issue by KakashiSensei** [bp74/StageXL#195]
Hi,

I am trying to use the Scale9Bitmap but it is working same as simple scaling of Bitmap. Please check, I am using this code

Bitmap newWhiteBitmap = new lib.WhiteBGAsset();
BitmapData newWhiteBitmapData = newWhiteBitmap.bitmapData;

Scale9Bitmap whiteScale9Bitmap = new Scale9Bitmap(newWhiteBitmapData, new Rectangle(0, 0, newWhiteBitmap.width.ceil(), newWhiteBitmap.height.ceil()));
whiteScale9Bitmap.width = whiteBitmap.width;
whiteScale9Bitmap.height = whiteBitmap.height;
whiteContainer.addChild(whiteScale9Bitmap);

**Comment by bp74** [comment]
Hi, It seems that you don't use the correct rectangle. The Rectangle you provide in the Scale9Bitmap constructor defines the inner rectangle of the BitmapData that is scaled in length or height. If you use the full size of the BitmapData you can use a standard Bitmap too. Take a look at the following code snippet: 

    var bitmapData = new BitmapData(48, 48, true, Color.Red);
    new Scale9Bitmap(bitmapData, new Rectangle<int>(12, 12, 24, 24))
      ..width = 300
      ..height = 300;

The BitmapData has a size of 48x48 and the rectangle is from 12,12 to 36,36 - you have 12 pixels on the left, top, right and bottom which are not scaled. The pixel between are scaled in width and height - that's how scale9 works.

I searched google for a simple scale9 sample and found this one.
http://feathersui.com/help/scale9-image.html
