### ISSUE TITLE
RenderTexture.fromImageElement adds up to each other

### ISSUE THREAD

**Issue by nilsdoehring** [bp74/StageXL#198]
Hey Bernhard,

The Gist linked below shows a glitch that got introduced with StageXL 0.11.0 (exactly that version). What's weird though, it just affects Chrome with WebGL RenderEngine. Still works in Firefox. [didn't test IE and Mobile for now]

How it looks on Chrome since 0.11.0
![bildschirmfoto 2015-06-12 um 00 59 24](https://cloud.githubusercontent.com/assets/1327275/8120359/8b574d6c-109e-11e5-9472-b42fb2d4239f.png)

How it should look:
![bildschirmfoto 2015-06-12 um 00 59 04](https://cloud.githubusercontent.com/assets/1327275/8120320/19f54fc0-109e-11e5-85a0-192bd8567e15.png)

https://gist.github.com/nilsdoehring/47af7dceef8eb5cc8308
[example only compatible from 0.12.0-dev onwards]

I can only assume it's related to changes that were made to RenderTexture: https://github.com/bp74/StageXL/commit/5a53562388abc8deedddfa98d50256186e55eb3f#diff-cb073eff55fa94d60fcca611d0a05e6b

Any idea what might cause this?

**Comment by bp74** [comment]
very strange. i will take a look at it as soon as possible!

**Comment by bp74** [comment]
I did some tests and i see the same problem, but i have no idea why this is happening. Looks like s bug in Chrome. The images are loaded correctly but when uploaded to the WebGL texture something is wrong. If you do this, it works correct - but it's just a workaround:

    imageElement.onLoad.listen((c) {
      _renderTexture = new RenderTexture.fromImageElement(imageElement);
      _renderTexture.canvas; // this copies the image to a canvas
      _renderTextureQuad = _renderTexture.quad;
    });

**Comment by bp74** [comment]
It also works if the SVGs have different size :/

**Comment by bp74** [comment]
I think this is what's going on: When Chrome copies the SVG image to a WebGL texture, a temporary memory blob is used internally.  The vector graphics is rendered to this memory before it is transferred to the GPU. 

This memory is reused for subsequent SVG images if the size does not change. If the subsequent SVG image has a different size a new memory blob is allocated. Unfortunately this temporary memory is not cleared before a new SVG image is rendered.

If the SVG image is rendered to the screen or to a canvas element this does not happen because the SVG image can be rendered to those surfaces directly.

**Comment by bp74** [comment]
We are not the first who have found this problem:
https://www.khronos.org/bugzilla/show_bug.cgi?id=1297

There is an old issue on the chromium issue tracker who addressed a problem where the SVG image wasn't drawn to the WebGL texture at all. The issue talks about a bitmap buffer that is used internally to render the SVG before uploading it to WebGL:
https://code.google.com/p/chromium/issues/detail?id=309161

I haven't found a new issue on the chromium issue tracker talking about this issue. Probably we should open a new one. It's not simple to create a repro case to show the problem, but it would be probably enough to show a compiled Dart sample.

**Comment by bp74** [comment]
Tried to write an issue, let's see what they say:
https://code.google.com/p/chromium/issues/detail?id=500180

**Comment by nilsdoehring** [comment]
Thank you so much for looking into this! Keen on the outcome of the bug report you filed – until then, the workaround does the trick.

**Comment by bp74** [comment]
Wow, they just released a patch for Chrome :)

**Comment by bp74** [comment]
FInally Chrome 47 was released which fixes this browser issue. 
The repro sample works fine now: http://www.stagexl.org/temp/example18/example18.html
