### ISSUE TITLE
How to remove BitmapData from the memory

### ISSUE THREAD

**Issue by KakashiSensei** [bp74/StageXL#200]
I am making an app which has multiple html5 games which I am loading on webview, but after 2-3 games app crashes giving memory warning. It seems that the loaded asset is not getting cleared even after the webview is removed. Is there a way to dispose the bitmapdata, sound and text file loaded through the asset manager? I can't find any function related to dispose.

**Comment by bp74** [comment]
In general memory is garbage collected as soon as you remove the last handle to the asset. There isn't much you can do other than that except those things:

If you use WebGL you can dispose the memory allocated on the GPU. You can do this by calling the dispose method on the RenderTexture: bitmapData.renderTexture.dispose();

Keep in mind that the ResourceManager also keeps a handle on your images and sounds. So if you want to remove those images and sounds from memory you have to release the ResourceManager be just setting it to Null or just don't have an handle to it.

Of course you can try to look at the F12-tools in your browser and try to profile where the memory is going, but that's not always as easy as it should be.
