### ISSUE TITLE
TextField with filter not high definition

### ISSUE THREAD

**Issue by xavierhainaux** [bp74/StageXL#201]
Hello Bernhard,
Here is a screenshot of 2 textfields on an iPhone.
The second one has a DropShadowFilter and as you can see it is looks blurred.

![img_0009](https://cloud.githubusercontent.com/assets/5110923/8304104/979cb068-19a3-11e5-8e14-bd714e0f2ac0.PNG)

It seems this is because TextField with filter lose the hiDpi feature.

Here is the source code: https://gist.github.com/xavierhainaux/75aa918a14d19b919ed7

Do you think this is something that could be fixed easily?

**Comment by bp74** [comment]
Hmmmm ... yes you are right. Filters are always calculated with a pixel ratio of 1.0 ... i was thinking about this some time ago but i forgot about it. It shouldn't be difficult to fix it, probably just a few lines of code - but they need to be on the right place :) I will take a look at it over the next few days! Thanks for reminding me.

**Comment by bp74** [comment]
Hi Xavier, 

I've committed some changes to enable HiDpi for filters. Previously filters who need a temporary frame buffer (like DropShadow, Blur, ...) were rendered with a 1:1 scale from the DisplayObject to the frame buffer. Not only HiDpi displays, but also the standard scaling of display objects should change this behavior. Now we render the display object to the temporary frame buffer that matches the scaling of the display object. Please give it a try!

Bernhard

**Comment by xavierhainaux** [comment]
It seems perfect. We have a neat TextField now.

Thank you for the quick fix.

**Comment by bp74** [comment]
Fix released with version 0.12.0+1
