### ISSUE TITLE
RenderState.renderTriangle and color/alpha

### ISSUE THREAD

**Issue by nilsdoehring** [bp74/StageXL#202]
Hi Bernhard,
RenderState.renderTriangle does seem to have a glitch somewhere when dealing with alpha on FFFFFF colors. See the Gist and Screenshot.Do you have an idea where this might come from?

https://gist.github.com/nilsdoehring/014b36e26d919dc0d2d9#file-webgl_triangle_color_bug-dart

![webgl](https://cloud.githubusercontent.com/assets/1327275/8312798/16ce32e0-19df-11e5-92f4-ef680b7c4139.png)

thanks,
Nils

**Comment by bp74** [comment]
Hi,

This looks like a problem with the premultiplied alpha. I did a very quick test which looks promising but i didn't do many tests.

    File   : src/engine/render_program_triangle.dart.
    Method : renderTriangle

    num colorA = colorGetA(color) / 255.0 * alpha;
    num colorR = colorA * colorGetR(color) / 255.0;
    num colorG = colorA * colorGetG(color) / 255.0;
    num colorB = colorA * colorGetB(color) / 255.0;

This pre-multipies the RGB values with the alpha value.

**Comment by bp74** [comment]
Maybe it's a little bit cleaner to change the GLSL fragment shader code instead:

    void main() {
      // gl_FragColor = vColor;
      gl_FragColor = vec4(vColor.rgb * vColor.a, vColor.a); 
    }

**Comment by bp74** [comment]
The changed shader code fixes the problem. I have committed a new change list.
