### ISSUE TITLE
Transparent Stages with WebGL not working correctly

### ISSUE THREAD

**Issue by bp74** [bp74/StageXL#207]
If you use the Color.Transparent for a Stage rendered with WebGL, you get a white background.

    StageXL.stageOptions.backgroundColor = Color.Transparent;
    StageXL.stageOptions.transparent = true;
    var stage = new Stage(canvasElement);

**Comment by bp74** [comment]
We have forgotten to premultiply the the pixels when we clear the WebGL context. If you use the value 0 instead of Color.Transparent it works fine - obviously this needs to be fixed.

    StageXL.stageOptions.backgroundColor = 0;
    StageXL.stageOptions.transparent = true;
    var stage = new Stage(canvasElement);

**Comment by bp74** [comment]
Fix released with version 0.12.0+1

**Comment by meibegger** [comment]
great - thanks a lot!

**Comment by meibegger** [comment]
updated, but still the same ...
0 works just fine!

**Comment by bp74** [comment]
Are you sure that you are using version 0.12.0+1 ?

Please check if your local copy of StageXL contains this line of code:
https://github.com/bp74/StageXL/blob/master/lib/src/engine/render_context_webgl.dart#L108

**Comment by meibegger** [comment]
yes pretty sure.
my local copy contains the code.
and i even used a new browser to check, just in case there was a cache-issue with my chromium ...

**Comment by bp74** [comment]
Do you have a simple repro case to test it? 
It works perfectly fine with my test application.

**Comment by meibegger** [comment]
sure!
index.html:
```
<!DOCTYPE html>
<html>
<head>
  <style>
    body { background: #00F; }
  </style>
</head>
<body>
  <main>
    <h1>Videocanvas</h1>
    <canvas id="stage" width="800" height="600"></canvas>
  </main>
  <script async type="application/dart" src="main.dart"></script>
  <script async src="packages/browser/dart.js"></script>
</body>
</html>
```

and main.dart:
```
import 'dart:html' as html;
import 'package:stagexl/stagexl.dart';

void main() {
  StageXL.stageOptions.renderEngine = RenderEngine.WebGL;
  StageXL.stageOptions.backgroundColor = Color.Transparent; // setting this to 0 works!
  StageXL.stageOptions.transparent = true;
  var canvas = html.querySelector('#stage');
  var stage = new Stage(canvas);
  var renderLoop = new RenderLoop();
  renderLoop.addStage(stage);
}
```

**Comment by bp74** [comment]
Hi, I'm confused :)

I started your repro case and i saw the same problem. I did some debugging and everything looked correct (in the code). And suddenly it started to work !?!? 

First i started the test in Dartium and the background was not transparent.
Then i started the test in Chrome (which triggers dart2js) and it looked correct!
And i don't know if it started to work immediately in Dartium or if i cleared the browser cache.

But for some strange reason it started to work without changing anything in StageXL!
Please try the same thing - start it in Chrome and clear the browser cache in Dartium.

**Comment by meibegger** [comment]
Hi :)

i already opened it in Chrome this morning, because i never used it for testing any dart before - so to be sure, everything is fresh.
very sad to: it did not work this morning, and it does not work now ... 

i also (re)cleared the Chromium cache - and it did not change anything ... ??

btw: are you Vienna-based? - your name sounds somehow familiar ...

**Comment by bp74** [comment]
This is really strange, what is going on here ... let me check again!
I'm not from Vienna but from Austria, i'm from Gmunden in Upper Austria :)

**Comment by meibegger** [comment]
maybe the graphic card ... 
i have
Intel Iris Pro Graphics
NVIDIA GeForce GT 750M with 2GB of GDDR5 memory and automatic graphics switching

But again ... setting the color to 0 works!

**Comment by bp74** [comment]
I did the test again with your sample - please try this one:
http://www.stagexl.org/temp/stagetest/index.html

Source:
http://www.stagexl.org/temp/stagetest/stagetest.zip

I have added a red square to have something on the stage.

**Comment by meibegger** [comment]
works!
(ich schau mir dein zip gleich an ... muss nur schnell in den supermarkt ... )

**Comment by meibegger** [comment]
the only difference was your build-folder (phpStorm :) ).
after building a release, my local version also works as expected ..

**Comment by bp74** [comment]
Does it also run without a build?

**Comment by meibegger** [comment]
yes it did

**Comment by bp74** [comment]
Great, so i will close the issue again, but don't hesitate to add a comment if there is still something strange.

**Comment by meibegger** [comment]
thanks!
