### ISSUE TITLE
StageXL's canvas flashes black on start

### ISSUE THREAD

**Issue by cubuspl42** [bp74/StageXL#217]
When I create a Stage object and select the WebGL backend, the canvas flashes black and then shows the correct stage. Is this necessary? Is there any way to fix this?

**Comment by bp74** [comment]
This is a very good question. I noticed it before but never checked if this can be avoided. The canvas is initialized for WebGL but we render the scene at the first callback of "requestRenderFrame". So there is a gap between initialization and the first render event. 

The code we need to change ist this (src/display/stage.dart)

    _renderContext = _createRenderContext(canvas, options);
    _renderContext.clear(backgroundColor); // new
    _renderState = new RenderState(_renderContext);

I will test it later today and will report what i found out.

**Comment by bp74** [comment]
Okay i already had a few minutes to try it out and it already looks much better. I did a commit to the master branch of StageXL with the change: 45742b8a9568ea31314f3d41a7aafb1f88eb2bc8

You could try to run your application with the master branch of StageXL on GitHub and see if it solves the black flicker in your setup too.

**Comment by cubuspl42** [comment]
I can't see any difference :(

**Comment by bp74** [comment]
Did you use the master branch or the code snippet from above?

**Comment by cubuspl42** [comment]
Master branch.
I've managed to make the flicker disappear - it was showing because I was modifying `canvas.width`/`height` before stage creation. If I wait with canvas manipulation until scene creation, your fix works. Thanks!

**Comment by bp74** [comment]
okay this is strange. Btw. best practice is not the change the width/height of the canvas, but the width/height of the canvas style! The width/height of the canvas style will control the visible size of the canvas and the width/height of the canvas will control how many horizontal and vertical pixels are used to render the canvas. StageXL will control the width/height of the canvas based on the width/height of the canvas style.

    // x and y are adjusted automatically by StageXL
    <canvas width="x" height="y" style="width:100%; height:100%" />

Use the StageAlign and StageScaleMode enums to control the scaling and alignment of the Stage on the canvas.

**Comment by cubuspl42** [comment]
That works great! Thank you. I think that the issue can be marked as resolved, because there is no flickering when things are done correctly.

**Comment by bp74** [comment]
Great! I'm happy to hear that it works now. Don't hesitate to send more issues/questions.
