### ISSUE TITLE
Keyboard events not firing

### ISSUE THREAD

**Issue by mnordine** [bp74/StageXL#219]
Keyboard events don't seem to be firing:

https://gist.github.com/mnordine/cbdcbd813ec6ba3723f7

**Comment by bp74** [comment]
Please try to set the display object that has the focus.

    stage.focus = myDisplayObject:

**Comment by mnordine** [comment]
It works if I do that, but this raises 2 possible bugs:

- Key listeners don't work on stage
- Clicking on an InteractiveObject and hitting a key won't fire an event

**Comment by bp74** [comment]
The idea is that you create an InteractiveObject (like Sprite, TextField, ...) and if you click on it, you can change the focus by setting the stage.focus property. Once you have set the focus you will receiver KeyboardEvents on this InteractiveObject. 

You could also to stage.focus = stage which will fire all KeyboardEvents on the stage.

**Comment by mnordine** [comment]
Why not do `stage.focus = target` when it's clicked? That way you align with developer expectation, as well as how Flash works. The developer then doesn't have to manually manage this for every object. Also, it should prob do `stage.focus = stage` whenever a stage is created, or at least whenever there is 1 stage.

**Comment by bp74** [comment]
Because it's not correct to change the focus automatically. It's up to the developer or the UI framework to do this, but it's not right to change the focus automatically in StageXL

**Comment by mnordine** [comment]
My apologies Bernhard, after I checked, Flash actually doesn't set the focus on click either. You have to uncomment `stage.focus = container` in the following gist for it to work:

https://gist.github.com/mnordine/57712a02f956bcb5893b

And I probably have always just added key listeners to the stage while using Flash, so what really tripped me up was that you have to do `stage.focus = stage` in StageXL, which is kind of weird.

**Comment by bp74** [comment]
Yes i was pretty sure that i have checked the behavior in Flash when i did the implementation, i'm happy that Flash actually does it the same way. It would be an easy change to set the focus by default to the stage itself, i will probably change this.
