### ISSUE TITLE
alignPivot

### ISSUE THREAD

**Issue by mnordine** [bp74/StageXL#221]
Starling has a really nice convenience function, DisplayObject.alignPivot():

https://github.com/Gamua/Starling-Framework/blob/master/starling/src/starling/display/DisplayObject.as#L379

Called with no args, it centers the pivot point. This would be nice to have for StageXL.

**Comment by bp74** [comment]
Thanks for the suggestion. Yes that would be a nice feature to add and it's also very simple, i will do it over the next few days.

**Comment by mnordine** [comment]
Great, thanks!

**Comment by bp74** [comment]
This feature was released with version 0.13.1
