### ISSUE TITLE
graphics.dart, fillGradient wrong return type

### ISSUE THREAD

**Issue by mikkeldamsgaard** [bp74/StageXL#225]
Hi

If seems that fillGradient and fillPattern in the Graphics object does not return the correct type.

  GraphicsPattern fillPattern(GraphicsPattern pattern) {
    var command = new GraphicsCommandFillPattern(pattern);
    this.addCommand(command);
    return command;
  }

Should be
  GraphicsCommandFillPattern fillPattern(GraphicsPattern pattern) {
    var command = new GraphicsCommandFillPattern(pattern);
    this.addCommand(command);
    return command;
  }

**Comment by bp74** [comment]
oh, good catch! I wonder why the analyzer didn't warn me. I will fix it asap!

**Comment by bp74** [comment]
This was released with StageXL 0.13.3
