### ISSUE TITLE
WebGL error with latest Dartium

### ISSUE THREAD

**Issue by frankpepermans** [bp74/StageXL#228]
An exception is thrown when RenderContextWebGL is being created:

Failed to execute 'uniformMatrix4fv' on 'WebGLRenderingContext': No function was found that matched the signature provided.

**Comment by bp74** [comment]
Yes there is a bug in Dartium 45 (the one that is shipped in the DEV-channel)
https://github.com/dart-lang/sdk/issues/25797

I hope they will fix it in the next DEV-channel release.

**Comment by bp74** [comment]
I did a test with 1.15.0-dev.5.0.0 and it seems that WebGL is working fine now.
