### ISSUE TITLE
Graphics Rectangle does not always draw from its origin point correctly

### ISSUE THREAD

**Issue by Joshua-Ferguson** [bp74/StageXL#229]
I noticed that if I draw a rectangle from (0, 0) that its left side gets clipped off (as if its drawing at (-1, 0)). I ignored it, thinking it was a chrome / dartium bug (I tried it in both), until I noticed the same issue occurring with my scrollbars, which were position by a grid control in the middle of the screen  (very similar to WPF's grid control: I am playing with making a simple GUI with StageXL); I found adding 0.01 to everything solves the issue, but I don't think that's a healthy way to fix the bug.

I investigated further, and found that at 0.00199 (to only 5 digits of accuracy) is when it first pops over to being drawn from (0, 0) (vs (-1, 0)).

I created a test image to show the issue, and I found further oddities around 0.00199 (in picture). I also tried integer rectangles (not sure if Dart VM converts them to doubles to match JS or not), and I got the same behavior as x = 0.0, so every line is just drawn 1 pixel early (but as long as its uniform, I suppose no one would notice).

(sorry for the blank space..., also that weird gradient you see in some of the images is from the Windows snipping tool's cross hair dropping a shadow)
![stagexl issue](https://cloud.githubusercontent.com/assets/7284858/13381444/7835ae40-de2a-11e5-97da-efe12ed4150c.png)

Code is as follows:

```
Sprite createTestSprite() {
  var sprite = new Sprite()
    ..x = 0.00199
    ..y = 0.0
  ;

  drawTestRectangle(sprite, new Rectangle(0.0, 0.0, 10, 10));
  drawTestRectangle(sprite, new Rectangle(0.0, 0.0, 20, 20));
  drawTestRectangle(sprite, new Rectangle(0.0, 0.0, 30, 30));

  return sprite;
}

void drawTestRectangle(Sprite sprite, Rectangle<double> rectangle) {
  sprite.graphics
    ..beginPath()
    ..rect(rectangle.left, rectangle.top, rectangle.width, rectangle.height)
    ..closePath()
    ..strokeColor(Color.Black, 1)
  ;
}

void main() {
  var canvas = html.querySelector('#stage');
  var stage = new Stage(canvas)
    ..scaleMode = StageScaleMode.NO_SCALE
    ..align = StageAlign.TOP_LEFT
  ;

  stage.addChild(createTestSprite());
}

<body style="overflow: hidden;">

  <canvas id="stage" width="800" height="600" style="width:100%; height: 100%;"></canvas>

</body>
```

Console output: `StageXL render engine : RenderEngine.WebGL`

**Comment by Joshua-Ferguson** [comment]
To further the mystery, I found the antialiasing option, and if you have `x = someInteger + 0.5`, all the lines work and they're really crisp. If you have `x = someInteger` all the lines are smeared.

Okay, so I think this might be a PICNIC (_just realized it as I was typing the first line_). Okay, so... 
![stagexl issue 2](https://cloud.githubusercontent.com/assets/7284858/13383587/e9614000-de59-11e5-824a-6e81a9eb27ca.png)
(awesome MS Paint picture)

I was thinking of as my mental model, for 1 pixel lines, that the stroke was drawn like in diagram 1, when really its drawn like diagram 2. Then, I'm gonna guess that the weird artifacts I'm seeing are just weird pixel + stroke --> integer (maybe by way of rounding?? so sometimes we get a line width of zero) issues.

**Comment by bp74** [comment]
Thanks for the question and your detailed analyses. I think everything you said is correct, it's all related to the alignment of the lines. Drawing lines seems easy but it's hard especially for thin lines and the WebGL renderer (please not that you can also activate the Canvas2D renderer which may be better suited if you draw lot's of thin lines and also need anti aliasing).

There is a nice picture which shows the alignment problem for thin lines - which is the same for the WebGL and Canvas2D renderer in StageXL. Please take a look here: https://github.com/bp74/StageXL/issues/23

Best practice to get thin (1 pixel) lines is to start from 0,5x0,5 coordinates, which is the center of a pixel. The line is drawn to the left and right and therefore you get a crisp line without anti aliasing.

**Comment by Joshua-Ferguson** [comment]
Cool.
