### ISSUE TITLE
Stage works in wrong coordinates sysytem after window resize

### ISSUE THREAD

**Issue by unco-games** [bp74/StageXL#250]
As test i just add matrix 10x10 with dots. Test-code and result pics related.

["main.dart" code](https://gist.github.com/unco-games/8d6d32160ae3e6193fed8f6d988d5abc)

[pure canvas full size window](https://unco-games.me/pub/8d6d32160ae3e6193fed8f6d988d5abc/pure_canvas_full.png)
[pure canvas resized window](https://unco-games.me/pub/8d6d32160ae3e6193fed8f6d988d5abc/pure_canvas_resize.png)

[StageXL canvas full size window](https://unco-games.me/pub/8d6d32160ae3e6193fed8f6d988d5abc/stagexl_full.png)
[StageXL canvas resized window](https://unco-games.me/pub/8d6d32160ae3e6193fed8f6d988d5abc/stagexl_resize.png)

Packages:
- html 0.12.2+2
- stagexl 0.13.10+2

Enviroment:
- OS: Windows 10 x64
- IDE: WebStorm 2016.2.2
- Dart SDK: 1.19.0
- Dartium: 45.0.2454.104 or Chrome: 52.0.2743.116 m

**Comment by unco-games** [comment]
I solved problem with add width and height parameters in Stage constructor and "position: fixed" property in canvas style. But nobody no one tutorial said about it. ((( Issue can be closed.

**Comment by bp74** [comment]
Thanks for the question. The Stage coordinates and the scaling are sometimes confusing. Especially if people had used PixiJS before, because things work differently in StageXL. The first rule is: Don't change the Stage size yourself, but use the built in Stage scaling options. You can learn more about it here:

http://www.stagexl.org/docs/wiki-articles.html?article=stagescale

I will prepare a small sample for your use case an post it here i little bit later.

**Comment by bp74** [comment]
I have added a new example:
https://github.com/bp74/StageXL_Samples/tree/master/example/basic/stage_size

Please take a look at the index.dart file and play with this configurations:

```
  // configure StageXL stage scale mode

  StageXL.stageOptions.stageScaleMode = StageScaleMode.SHOW_ALL;
  //StageXL.stageOptions.stageScaleMode = StageScaleMode.EXACT_FIT;
  //StageXL.stageOptions.stageScaleMode = StageScaleMode.NO_BORDER;
  //StageXL.stageOptions.stageScaleMode = StageScaleMode.NO_SCALE;

  // configure StageXL stage align

  StageXL.stageOptions.stageAlign = StageAlign.NONE;
  //StageXL.stageOptions.stageAlign = StageAlign.TOP_LEFT;
```

Hope this helps and please don't hesitate to ask more questions.

**Comment by unco-games** [comment]
Thank you for the quick reply and right direction of self-explore. I think issue can be closed.

**Comment by bp74** [comment]
Happy to hear  that it helped.

**Comment by bp74** [comment]
@unco-games I had a quick look at your Hide & Seek Alphabet game. Looking forward to play it :) 

Just a quick comment: I saw that you create the stage with the clientWidth and clientHeight of the html body on startup. Be sure that this is the right thing for your game. In practice it is much easier to use a fixed size of the stage (like 800x600). This defines the coordinate system of the stage, it does not define the actual pixels. Placing your display objects at a location is much easier if the coordinate system has a known size. If you create the stage with the clientWidth and clientHeight the coordinates are different on every startup.

If the browser window (or the canvas element) is resized, the stage is rendered with more pixels but the coordinate system is still the same - as said earlier, this makes it easier to work with the display objects in your display list/tree.

Of course there are exceptions - for example if you use the StageScaleMode.NO_SCALE. But for most use cases it's easier to start with a given size of the coordinates system of the stage. Hope this helps...

**Comment by unco-games** [comment]
@bp74 this game i`m trying to create for my 2 y.o. daughter and gameplay may be too boring for you. 

Thank you for code review. You are right, fixed coordinate system for in-browser-game more usefull, but i planned use this code on mobile devices (iOS tablets first of all). Hope Flutter can hepls me and i will be able to use StageXL-code with them.
