### ISSUE TITLE
Resource manager gives wrong BitmapData

### ISSUE THREAD

**Issue by unco-games** [bp74/StageXL#251]
I`m trying to load three SVG files and add it in DisplayObjectContainer. But each next image loaded over previous.

Code: [main.dart](https://gist.github.com/unco-games/30bb21287ba3517574a724d65c5a3f1d)
Picture: [screenshot](https://unco-games.me/pub/8d6d32160ae3e6193fed8f6d988d5abc/image_over_image.png)

Packages:
html 0.12.2+2
stagexl 0.13.10+2

Enviroment:
- OS: Windows 10 x64
- IDE: WebStorm 2016.2.2
- Dart SDK: 1.19.0
- Dartium: 45.0.2454.104 or Chrome: 52.0.2743.116 m

**Comment by bp74** [comment]
We had this issue some time ago:
https://github.com/bp74/StageXL/issues/198

It was a browser bug that was fixed with Chrome 47.
I think Dartium is not yet updated to Chrome 47 (but i may be wrong).

Have you tried it in Chrome and Firefox?

**Comment by bp74** [comment]
Yes, Dartium is based on Chrome 45 where this bug is not fixed.
It should work fine in Chrome and Firefox

**Comment by unco-games** [comment]
Yes, you are right, new Chrome works correct.
I'm a fool, I thought, that browser for Dart should ideally work with Dart. Will try to use PNG instead of SVG.

**Comment by bp74** [comment]
A workaround for Dartium could look like this:

```
var optionsBitmapData = resourceManager.getBitmapData('options');
optionsBitmapData.renderTexture.canvas; // workaround
var options = new xl.Bitmap(optionsBitmapData);

```
The access to the canvas forces the SVG to be copied to a Canvas Element before it is copied to a WebGL texture. This will work around the browser bug in Dartium 45.

**Comment by bp74** [comment]
Yes that's a very unfortunate bug in Dartium. 
I hope they will update Dartium to a much newer version soon.
