### ISSUE TITLE
Contrast bug or misunderstanding

### ISSUE THREAD

**Issue by RobertMcDermot** [bp74/StageXL#252]
I am trying to make use of the ColorMatrixFilter's adjustContrast method. When giving it positive values (between 0 and 1) I am getting the result I expect. However, when giving it negative values (between -1 and 0) I am not getting the result I expect.

For the negative values case, as the value decreases, the images alpha value also decreases until at -1 it is completely invisible. I would expect that at -1 the image would still be completely opaque, just have less contrast.

Here is a repo that demonstrates the results that I am seeing: https://github.com/RobertMcDermot/stagexl_contrast_bug. Please advise if I am misunderstanding or misusing the feature or if there is a bug that is causing my results. Below is the rendered result from executing the code in the repo.

![rendered_result](https://cloud.githubusercontent.com/assets/5414318/18220696/984b5a3a-7142-11e6-9f29-8301068353ca.png)

**Comment by bp74** [comment]
Hi, yes i think you are right. I also don't understand why the alpha changes. 
Thanks a lot for the repro case, i will start investigating immediately.

**Comment by bp74** [comment]
It was indeed a bug in the ColorMatrixFilter. 
I have fixed it and uploaded a new version of StageXL to Pub. 
Btw. your game "Children Of Ur" looks amazing!
