### ISSUE TITLE
Please publish!

### ISSUE THREAD

**Issue by kevmoo** [bp74/StageXL#256]
I have Pop, Pop, Win! working w/ the dev compiler – but only when I pin to HEAD. 😄

**Comment by bp74** [comment]
Hi, I have publish verison 0.13.12. Is it possible to play Pop Pop Win on Chrome with ES6 code? That's pretty awesome, will take a look at the generated code for sure!

**Comment by kevmoo** [comment]
Feel free to close this!

I will do a write-up on running PPW w/ our bazel stuff shortly.

A request: could you tag your releases on GitHub? It'd be great to see which commit corresponds to which release.

**Comment by bp74** [comment]
Yes that's a good idea, i will do this!
