### ISSUE TITLE
Type checking issues in graphics get bounds 

### ISSUE THREAD

**Issue by overdub** [bp74/StageXL#264]
I just had some type checking issues throwing exceptions in Dartium at get bounds in graphics_context_bounds.dart and graphics_mesh_segment.dart. Changing `return new Rectangle<double>` to `return new Rectangle<num>` fixes them.

**Comment by bp74** [comment]
hi, 
I think this should be fixed in StageXL 1.1 
Please check if you are working with the latest version.

**Comment by overdub** [comment]
Sorry, my bad. Thought I was on 1.1.0 but really wasn't. It's fixed in 1.1.

**Comment by bp74** [comment]
No problem :)
