### ISSUE TITLE
How to properly remove a class from memory

### ISSUE THREAD

**Issue by mayorbyrne** [bp74/StageXL#274]
I tried to simplify this as much as I could. Given the following:

```js
library demo;

import 'dart:html' as html;
import 'package:stagexl/stagexl.dart';

part 'aaaatest.dart';

AAAATest _aaaaTest;

Stage stage = new Stage(html.querySelector("#stage"), width: 1000, height: 1000);

void main() {
  RenderLoop renderLoop = new RenderLoop()
    ..addStage(stage);

  _aaaaTest = new AAAATest()
    ..addEventListener(MouseEvent.CLICK, _interact)
    ..addTo(stage);
}

void _interact(Event event)
{
  _aaaaTest.removeEventListener(MouseEvent.CLICK, _interact);
  _aaaaTest.dispose();
  _aaaaTest.removeFromParent();
  _aaaaTest = null;
}
```

Where AAAATest is
```js
part of demo;

class AAAATest extends Sprite
{
  AAAATest()
  {
    new Sprite()
      ..graphics.rect(0, 0, 500, 500)
      ..graphics.fillColor(Color.Black)
      ..addTo(this);
  }

  dispose()
  {
    this.removeChildren();
  }
}
```

When I run this, I open up the dart vm observatory and click on `Allocation Profile` and find the class in the list. When I click the rectangle on the screen, it is removed. Then I click `GC` in observatory, and the "currently allocated instances" of `AAAATest` correctly gets reduced to 0. Every line in the _interact method is required for this number to go down.

The issue I'm having is that if I change the first line of AAAATest() to new Shape(), refresh the page and observatory, and perform the above actions, the number does not get reduced. I cannot figure out why, and it sort of makes class disposal a guessing game. The weird part is if I have both the shape and the sprite in the class, it reduces to 0 properly as well. If you have any information that can help me out, I'd appreciate it. This might be related to the last issue I posted.

**Comment by bp74** [comment]
I wouldn't worry too much about it. First of all you will use Dartium only for development, later you have to compile to JavaScript anyway and your application will run on a JavaScript VM from Google, Microsoft, Apple or Mozilla. Those VMs and their GCs are completely different anyhow.

Have you tried of the object is garbage collected at a later time? Maybe the Dartium GC doesn't guarantee that an unused object is removed on the first GC pass? I don't think that the dispose-pattern is very much useful in a JavaScript world. It has advantages for example in .Net, but a JavaScript VM is allocating a lot of memory on each frame even if your application is doing nothing. Of course you shouldn't create big objects all the time and throw them away, but i wouldn't bother too much about it.
