### ISSUE TITLE
Document ViewportContainer

### ISSUE THREAD

**Issue by mnordine** [bp74/StageXL#279]
What is a `ViewportContainer`? Why should I use it instead of a `DisplayObjectContainer` with a `new Mask.rectangle()`? Also, I don't believe it's working right now, might be related to #277, #278.

**Comment by bp74** [comment]
You will get the same result as with DisplayObjectContainer and a rectangular mask. But the ViewportContainer is more light-weight. If the only mask you are using in your application is the one with the ViewportContainer, all the mask-related code in the main render code is removed by the dart2js tree-shaking and dead-code-elimination logic. I will take a look at the mentioned issues and also at the repro code you sent my be email today or tomorrow.

**Comment by bp74** [comment]
Oh, and one thing i have forgotten to mention: It also provides scrolling capabilities. So it's not exactly the same as DisplayObjectContainer with a rectangle mask, but it also scrolls to the x/y position of the viewport rectangle. Which makes it very useful for scroll lists.

**Comment by mnordine** [comment]
Oh, so it's like Flash's `DisplayObject.scrollRect` property in the latter regard?

**Comment by bp74** [comment]
Yes exactly like the DisplayObject.scrollRect property!

**Comment by mnordine** [comment]
What do you think about implementing the scrolling functionality as `DisplayObject.scrollRect`?

**Comment by mnordine** [comment]
> If the only mask you are using in your application is the one with the ViewportContainer, all the mask-related code in the main render code is removed by the dart2js tree-shaking and dead-code-elimination logic. I will take a look at the mentioned issues and also at the repro code you sent my be email today or tomorrow.

This sounds like it would increase run-time performance, not just save on code size, correct? (I need to target slow mobile devices, so every bit counts)

**Comment by bp74** [comment]
I hate the idea of DisplayObject.scrollRect :) We had this discussion and i will never do that! 

This feature is only needed on a few DisplayObjects, but if you add this property you would need to check it for every DisplayObject - regardless if it is used or not. This is also true for the DisplayObject.mask property. If i would do DisplayObject.mask today, i would probably not add it. Instead i would use a dedicated MaskedContainer (similar to ViewportContainer). This way you only need to to the check for mask for this single DisplayObject and not for all display objects.

Yes it's not only code size but even more for performance. Let's assume you have 1000 DisplayObjects on the Stage and only one uses the mask property (or scrollRect) - the render code would check every single one of the 1000 display objects if a mask or scrollRect is set. This is not efficient.

**Comment by mnordine** [comment]
In that case, I also hate `DisplayObject.scrollRect`, :)

**Comment by mnordine** [comment]
> all the mask-related code in the main render code is removed by the dart2js tree-shaking and dead-code-elimination logic

Have you verified this is indeed the case?

**Comment by bp74** [comment]
No, i just say random things as they come into my mind :)

Of course i verified it!! 
This is the hot function that get's simpler if you don't use the mask property:
https://github.com/bp74/StageXL/blob/master/lib/src/engine/render_state.dart#L120
