### ISSUE TITLE
Mouseclicks not working in Dartium (SDK 1.24)

### ISSUE THREAD

**Issue by nilsdoehring** [bp74/StageXL#280]
Hi Bernhard,

I have noticed that, if I compile my stuff with the most recent SDK (1.24.1), mouse click and over/out events are ignored in Dartium (tried v45 and v50) – Hand cursor is showing though. Scroll events still work, too. 

In Chrome after dart2js, everything is still running fine.
I'll try to circle in the issue and provide a repro case later tonight.

Nils

**Comment by nilsdoehring** [comment]
Found the culprit: I do checks for html.TouchEvent.supported, and they are always TRUE in Dartium when run with SDK 1.24.1. Filed the issue [here](https://github.com/dart-lang/sdk/issues/29997).

**Comment by bp74** [comment]
Interesting! Thanks for investigating.
