### ISSUE TITLE
Any way to pass json string instead of url in addTextureAtlas function?

### ISSUE THREAD

**Issue by marcinsydor** [bp74/StageXL#281]
I need to run my games from a local drive without a server. For the security reason, it's not possible to load json files locally. So I'm trying to find a way to pass json string to addTextureAtlas function with the latest stagexl lib. 
The games originally were built with stagexl ^0.9.0 and with a small path to the lib I was able to prevent loading the json files and use the json string. 
``` new Future.value(json).then((textureAtlasJson) {``` instead of ```HttpRequest.getString(url).then((textureAtlasJson) {``` in ```lib/src/util/resource_manager.dart``` file.

But It looks like the latest ResourceManager is more complex and I need more time to understand how the manager works now. I would be grateful for any your thoughts on this.

**Comment by bp74** [comment]
Hi,

Yes you can do this with a custom TextureAtlasLoader, please take a look at this file:
https://github.com/bp74/StageXL/blob/master/lib/src/resources/texture_atlas_loader.dart
Your custom loader probably would look a lot like the _TextureAtlasLoaderBitmapData.

Once you have your custom TextureAtlasLoader you can use the static TextureAtlas.withLoader method:
https://github.com/bp74/StageXL/blob/master/lib/src/resources/texture_atlas.dart

Maybe even the static TextureAtlas.fromBitmapData method works for you? This method let's you load a TextureAtlas where the JSON is in a string and the image of the texture atlas is in a BitmapData.

Hope this helps!

**Comment by marcinsydor** [comment]
Thanks Benhard. I have found some of that info and make some dir

**Comment by marcinsydor** [comment]
Thanks Bernhard. I've found some of that info and I was able to make some dirty amends to the forked lib. It seems to work but I'll try to achieve it without changing your lib. I hope that's possible. I will also have a look at TextureAtlas.fromBitmapData again. 
I have one more question. The game loads texture atlas bitmaps locally only if I set render engine to Canvas2D. With WebGL I'm getting a cross-origin error for the images.
```main.dart.js:1109 Uncaught DOMException: Failed to execute 'texImage2D' on 'WebGLRenderingContext': The cross-origin image at ... ```
Do you think there is a solution for this issue?

**Comment by bp74** [comment]
You get this error when you load the image from a different domain. If your server supports CORS you can enable it when loading the image/BitmapData. 

You can enable it globally in your application by doing this:

    StageXL.bitmapDataLoadOptions.corsEnabled = true;

Or you can create a new instance of BitmapDataLoadOptions when loading a certain BitmapData.

    var options = new BitmapDataLoadOptions()..corsEnabled = true;
    var bitmapData = await BitmapData.load(url, options);

**Comment by marcinsydor** [comment]
I think I was not clear here. I still have the same situation where I'm trying load bitmaps from local disk. If set render engine to WebGL value then I have the error which I mentioned. The good thing is the game loads bitmaps in Canvas2D mode. Enabling cors doesn't really help. I'm getting then an error which informs me that cors is not supported for file:/// protocol. Which makes sense to me. I can live with Canvas2D but I've tried to understand why I can't load bitmaps in WebGL mode from a local disk.

I've also tried to find a solution which let me load local audio files. So far I can do it only If I add audio  elements to html document. Then using querySelector and having AudioElements I can play or stop sounds. It works but it means I have two systems to managing audio files. It also means I need to update resources in all 10 games. The games still need to work in online and local mode. I'm wondering if there is a better way to do it.

**Comment by bp74** [comment]
Okay i see, unfortunately i don't know the answer how to make the file:/// resource work. I'm pretty sure you can search for it on StackOverflow because it is not a StageXL related issue.

**Comment by GoToLoop** [comment]
> ... I don't know the answer how to make the `file:///` resource work.

If it's in a Chrome-family browser, AFAIK, they've deliberately disallowed `file:///` scheme for its [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API)!
Dunno about other browser families but Firefox's [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) allows `file:///` scheme!  :relieved:
