### ISSUE TITLE
Make work StageXL with DDC

### ISSUE THREAD

**Issue by marcinsydor** [bp74/StageXL#282]
Hi Bernhard,
Are you playing to update the library to work with DDC? It would be great if we could debug them in Chrome. The most of the errors which I see links to nums and doubles. I might be wrong but looks like it would be not very hard to change it?

**Comment by bp74** [comment]
Hi, i thought that it works already. Do you have a few examples what does not work?

**Comment by marcinsydor** [comment]
I have to go now but I will send over something tomorrow.

**Comment by marcinsydor** [comment]
Looks like I won't be able to test it again until next week so I will close the issue for now.
