### ISSUE TITLE
Textfield can cut letters off on the left

### ISSUE THREAD

**Issue by kevin-quaver** [bp74/StageXL#283]
I've noticed if I have a TextField, a lowercase `j` will get cut off on the left. This looks especially bad if there is a stroke on the TextField. This also happens with `autosize = TextFieldAutoSize.LEFT`.

Here, I've placed two on the stage: one normal, and one with a `leftMargin` of 4.
```dart
  new TextField("just in time.", new TextFormat("Times New Roman", 26, Color.Black))
    ..width = 130
    ..height = 34
    ..border = true
    ..x = 20
    ..y = 60
    ..addTo(_stage);

  new TextField("just in time.", new TextFormat("Times New Roman", 26, Color.Black)
    ..leftMargin = 4)
    ..width = 130
    ..height = 34
    ..x = 20
    ..y = 20
    ..border = true
    ..addTo(_stage);
```
![capture](https://user-images.githubusercontent.com/21197438/30988889-6b3c34f8-a461-11e7-8d9c-bfc2a5997213.PNG)

Is there a happy solution, or do I have to check every time a TextField is changed and apply a new `TextFormat` with `leftMargin` if it starts with a certain character(s), provided other letters also get chopped?

**Comment by bp74** [comment]
Hi, i have to take a look at this and do some tests.  I will get back to you asap!

**Comment by bp74** [comment]
I did some tests with this issue and the bounding box of the "j" letter actually has a negative left value. Let me try to show this with this image:

![bounds](https://user-images.githubusercontent.com/1810450/33516011-7b979c9c-d76b-11e7-8122-cc9b0030fd7d.jpg)

As you can see, the lower part of the "j" intersects with the right side of the bounding box of the "a" character. So i don't see any other solution than using a left margin for all your text regardless of the first letter.
