### ISSUE TITLE
3D Framework

### ISSUE THREAD

**Issue by unicomp21** [bp74/StageXL#284]
Are there any dart projects which have something similar to the babylonjs feature set?  I've used ChronosGL, but I'd like PBR features, etc.

**Comment by bp74** [comment]
@nilsdoehring did a Dart interop facade packages for BabylonJS.
https://github.com/block-forest/babylonjs-dart-facade

But i'm not aware of any native Dart packages.

**Comment by unicomp21** [comment]
Thanks Bernhard!  Are there StageXL examples for displacement and normal
map filters?  Or a format description for the rgba values?

**Comment by bp74** [comment]
There are samples for filters, especially for the normal map filters. There is no example for the displacement filter, but it's not that difficult to use. The displacement filter takes a bitmap where the red and green channel is the displacement in x and y direction.
https://github.com/bp74/StageXL_Samples/tree/master/example/filter

**Comment by bp74** [comment]
Edit: There is an old example for all filters, almost forgot about it:
https://github.com/bp74/StageXL_Samples/tree/master/web/_old/filter

**Comment by unicomp21** [comment]
Thanks!
