### ISSUE TITLE
Screen flicker

### ISSUE THREAD

**Issue by unicomp21** [bp74/StageXL#290]
On Spine, Flump, and TextField demos I get a screen flicker each time I tap my old ipad.  How do I prevent the screen flicker?

**Comment by bp74** [comment]
Never heard of this problem. Does it only happen on old devices but not on new ones?

**Comment by unicomp21** [comment]
yes, only seems to happen on old ones, perhaps I just need a new ipad :)

**Comment by unicomp21** [comment]
ipad 2
mc769ll/a

**Comment by unicomp21** [comment]
Seeing the same flicker on my iphone 7
mg4n2ll/a

**Comment by unicomp21** [comment]
flicker appears to be due to canvas background color "popping" thru for an instant

**Comment by nilsdoehring** [comment]
This CSS rule should do the trick:
```
* {
    -webkit-tap-highlight-color: rgba(0,0,0,0);
}

```

**Comment by unicomp21** [comment]
perfect!  thanks!
