### ISSUE TITLE
 GainNode.gain.value setter deprecation warning in chrome

### ISSUE THREAD

**Issue by AndrewLugg** [bp74/StageXL#293]
In Chrome 63 (dev build). They have started showing a deprecation warning for GainNode.gain setter.

"Deprecation] GainNode.gain.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed. See https://www.chromestatus.com/features/5287995770929152 for more details."

You have it in your https://github.com/bp74/StageXL/blob/master/lib/src/media/implementation/web_audio_api_mixer.dart line 17

**Comment by bp74** [comment]
Thanks for the report, i will take a look asap!

**Comment by AndrewLugg** [comment]
Is there any updates on this?

**Comment by bp74** [comment]
sorry, i will address this over the weekend!

**Comment by bp74** [comment]
Okay it is done. New version is StageXL 1.3.0+1. I did some tests with different browsers and everything worked just fine. If there are any issues please report back. Thanks for the report about this issue!
