### ISSUE TITLE
StageXL doesn't upload TexturePacker atlases as RGBA 4444

### ISSUE THREAD

**Issue by mnordine** [bp74/StageXL#298]
Texture Packer outputs the following info in its json:

```json
"meta": {
	"app": "http://www.codeandweb.com/texturepacker",
	"version": "1.0",
	"image": "assets_main@2x.png",
	"format": "RGBA4444",
	"scale": "1",
}

```

Even though this info is present, StageXL doesn't upload as RGBA 4444, thus missing 2x reduction in GPU memory!

**Comment by bp74** [comment]
Will have a look at this. Thanks for pointing this out!

**Comment by bp74** [comment]
Would be an opportunity to support other texture compression algorithms too.

**Comment by mnordine** [comment]
I have a local branch that supports pvr textures, but not sure if it's architected as you'd like
