### ISSUE TITLE
TextField.width and .height are always 100

### ISSUE THREAD

**Issue by unco-games** [bp74/StageXL#300]
```Dart
TextField text = new TextField('SOME TEXT');
stage.addChild(text);
print(text.width);
print(text.height);
```

console:
```
100
100
```

**Comment by mnordine** [comment]
I believe this is the behavior in Flash as well. If you'd like to have it automatically sized, do:

```dart
text.autoSize = TextFieldAutoSize.LEFT;
```

**Comment by unco-games** [comment]
Ouch!
This is very unobvious if you did not work with Flash.
Thanks!

**Comment by bp74** [comment]
You should also specify the height to not waste any resources (memory). And yes, the default is always 100x100. You can also take a look at the textWidth and textHeight properties which tell you the actual size of the text.
