### ISSUE TITLE
Audio on Chrome not allowed by MEI policy

### ISSUE THREAD

**Issue by AndrewLugg** [bp74/StageXL#313]
Chrome is stopping allowing auto-playing audio, which is stopping audio from being played in StageXL. It doesn't seem to get caught with any errors currently. It is affecting us on our WebAudioAPI, we haven't done tests with HTML5 but from the documentation it seems it would effect both.

Here is some documentation on it:
https://www.chromium.org/audio-video/autoplay
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

**Comment by bp74** [comment]
Thanks for the report, link to same issue on the StageXL forum:
https://groups.google.com/forum/#!topic/stagexl/S5qZNj5Qpps
