### ISSUE TITLE
TextField with Shadows are incorrectly rendered with shadow property...

### ISSUE THREAD

**Issue by Krobill** [bp74/StageXL#34]
... and not with DropShadowFilter it seems. The dart toolkit exports correctly DropShadowFilters applied in Flash as a shadow property on symbol instances but the blur parameter is ignored and exported shadows are always sharp for texts.

If shadows are applied manually through the filter, it works correctly.

Not familiar enough yet with the low level canvas operations to spot the origin of the problem, sorry.

**Comment by bp74** [comment]
Just found this old issue and i'm happy to report that the Chrome team fixed the blur issue some time ago. Now Chrome does render shadows as the other browsers do.
