### ISSUE TITLE
Pop, Pop, Win! broken by 2.1.0 - something like `format` was assumed to be in the texture map

### ISSUE THREAD

**Issue by kevmoo** [bp74/StageXL#354]
Repro:

* https://github.com/dart-lang/sample-pop_pop_win
* Remove `stagexl` restriction in `pubspec.yaml`
* Run

See the crash in `_TextureAtlasFormatJson.load`

**Comment by AndrewLugg** [comment]
@mnordine is this connected with your changes on https://github.com/bp74/StageXL/pull/353?

**Comment by mnordine** [comment]
Yep, will fix....

**Comment by AndrewLugg** [comment]
2.1.1 has now been published on pub.dev with the changes.

Let us know if you have any more issues with it.

**Comment by kevmoo** [comment]
All good! thanks!
