### ISSUE TITLE
Bitmap Font support?

### ISSUE THREAD

**Issue by KakashiSensei** [bp74/StageXL#87]
Hi,
How can I use Bitmap font in StageXL. Is there any library for that?

**Comment by KakashiSensei** [comment]
Running the app on iPad and iPhone shows black flash when the TextField (Using web fonts) text is changed as it runs on canvas. Is there any way that black flash can be stopped.
http://playpowerlabs.org/lwactivities/BattleShip/

**Comment by bp74** [comment]
There is an open issue for this problem: issue #160

I would be very happy to fix this issue, unfortunately i don't own an iOS 8 device. If someone would like to donate an old/broken/slow phone (as long is it starts the browser) it would be a big help. I will also try to borrow a device from someone i know - most of my friends have Android ...

Btw. i like your battle shops games, very nice!!!

**Comment by bp74** [comment]
@KakashiSensei Any insight information would help too. Do you see the black flash only after an update of the TextField? This would mean that the texture upload is somehow delayed and this is the reason for the black block that is visible for a short period of time.

**Comment by KakashiSensei** [comment]
Yup it flashes when the textfield is updated. I will try to upload the recording.

**Comment by KakashiSensei** [comment]
check this video
http://scrapeshare.com/?vid=1428591153812-k6tbvm

**Comment by bp74** [comment]
Wow! It's the whole screen that flickers and not only the area where the text field is! Thanks a lot for this video. Do you see something on the console? Like a WebGL error or similar.

**Comment by KakashiSensei** [comment]
I am getting warning no error
WebGL: INVALID_ENUM: activeTexture: texture unit out of range

**Comment by KakashiSensei** [comment]
Can we have bitmap font support in stageXL. Bitmap font improves performance as compared to web fonts. The format which is normally used are generated from 
http://kvazars.com/littera/
http://www.bmglyph.com/

**Comment by bp74** [comment]
Okay that's interesting. This is not a real fix for the problem, but a quick test to see if this helps:

search the file src/engine/render_texture.dart
go to line 175

    _renderingContext.activeTexture(gl.TEXTURE10);

replace this with:

    _renderingContext.activeTexture(gl.TEXTURE3);

**Comment by bp74** [comment]
Reopen for the Bitmap Font Support request

**Comment by bp74** [comment]
It looks like the max. number of texture slots is 8 on the iPhone ... using 10 is a bad thing and the current implementation is not clean anyway.

**Comment by KakashiSensei** [comment]
Okay I have changed the code at two places

set filtering(RenderTextureFiltering filtering) {
    if (_filtering != filtering) {
      _filtering = filtering;
      if (_texture != null) {
        _renderingContext.activeTexture(gl.TEXTURE3);
        _renderingContext.bindTexture(gl.TEXTURE_2D, _texture);
        _renderingContext.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, _filtering.value);
        _renderingContext.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, _filtering.value);
      }
    }
  }

and 

void update() {
    if (_texture != null) {
      _renderingContext.activeTexture(gl.TEXTURE3);
      _renderingContext.bindTexture(gl.TEXTURE_2D, _texture);
      if (_textureSourceWorkaround) {
        _canvas.context2D.drawImage(_source, 0, 0);
        _renderingContext.texImage2DCanvas(
            gl.TEXTURE_2D, 0, gl.RGBA, gl.RGBA, gl.UNSIGNED_BYTE, _canvas);
      } else {
        _renderingContext.texImage2DUntyped(
            gl.TEXTURE_2D, 0, gl.RGBA, gl.RGBA, gl.UNSIGNED_BYTE, _source);
      }
      _renderingContext.bindTexture(gl.TEXTURE_2D, null);
    }
  }

It stopped flashing as it used to do but still screen flickers (sometimes not all the time) when textfield is updated

src/engine/render_frame_buffer.dart also has this line should I also replace them?

**Comment by bp74** [comment]
Okay good that it is better than before, so we are on the right way. The render_frame_buffer could be a problem if you are using filters. You can change it and see if it works better. Please also check the console if there are still errors when the screen flickers.

**Comment by KakashiSensei** [comment]
No error and warnings. And no flicker........yup its done thanks a lot. Working like charm.

**Comment by bp74** [comment]
AWESOME! Thanks for helping to fix the problem!
I will clean up the code and the next release of StageXL will contain all those changes.

**Comment by KakashiSensei** [comment]
Hey can you add BitmapTextField support in stageXL. Other HTML5 engine has this feature.

**Comment by bp74** [comment]
Sure, i have already reopened this issue to take a look at it.

**Comment by KakashiSensei** [comment]
Thanks a lot

**Comment by KakashiSensei** [comment]
Flickering still occurs when running the game inside the UIWebView of an app while it run smooth in the iOS browser.

**Comment by bp74** [comment]
Interesting, can you check if there is an error in the console?

**Comment by KakashiSensei** [comment]
No there is no error. I can see the flickering on the simulator but no warning and error on console. I have deleted and reinstalled app just to make sure there is no caching of previous version.

**Comment by KakashiSensei** [comment]
Game inside iOS browser
http://scrapeshare.com/?vid=1428770021617-n7lkbr

Game inside UIWebView
http://scrapeshare.com/?vid=1428770053355-3xx1qm

Game flickers when the textfield is updated it only occurs inside webview of an app. I tried to debug it but there was no warning and errors on console.

**Comment by bp74** [comment]
Very strange. You could try this:
Go to the file src/display/render_loop.dart

There is a method called "advanceTime" - please add a try-catch block in this function to catch all errors. Maybe we should do this anyway in the next release of StageXL. Anyway, try to catch an error here and output it with an alert or somehow.

The bleeding edge code on GitHub has a lot of chances including those things we have changed with the texture slot.

**Comment by KakashiSensei** [comment]
void advanceTime(num deltaTime) {
    try {
    _currentTime += deltaTime;

    _enterFrameEvent.passedTime = deltaTime;
    _enterFrameEvent.dispatch();

    juggler.advanceTime(deltaTime);

    for (int i = 0; i < _stages.length; i++) {
      _stages[i].juggler.advanceTime(deltaTime);
    }

    if (_invalidate) {
      _invalidate = false;
      _renderEvent.dispatch();
    }

    for (int i = 0; i < _stages.length; i++) {
      _stages[i].materialize(_currentTime, deltaTime);
    }

    _exitFrameEvent.dispatch();
    } catch(exception, stackTrace) {
      window.alert('test');
    }
  }

No alert but still flickers on textfield update

**Comment by bp74** [comment]
Currently i ran out of new ideas. If there is no error it will be very difficult to figure out what is going on. I thought that in iOS 8 the WebView is using the same browser engine as Safari is using. Obviously this is not the case :( I will do some Google search, maybe someone had the same problem.

**Comment by bp74** [comment]
You are probably using the WKWebView and not the UIWebView right?

**Comment by KakashiSensei** [comment]
ooops I am using UIWebView at present (this might be the reason for flickering). I will check with WKWebView and will update regarding the performance. 
Thanks

**Comment by bp74** [comment]
Yes i think this could solve the problem.  I wonder that the UIWebView even worked since Dart only supports the latest browsers. But to be honest I don't know a lot about those WebViews in iOS.

**Comment by KakashiSensei** [comment]
No change even after using WKWebView same flickering. I have added fps meter and the game is running on 30fps inside WKWebView while it is running on 60fps on device browser.

**Comment by bp74** [comment]
This is surprising. The WKWebView should be much faster than the UIWebView.

**Comment by bp74** [comment]
The guys from CocoonJS are using the WKWebView too:
http://blog.ludei.com/cocoonjs-announces-webview-for-ios-8-publish-wkwebview-powered-standalone-apps/

**Comment by KakashiSensei** [comment]
It was flickering because haven't included this line in the code
if (Multitouch.supportsTouchEvents) {
      Multitouch.inputMode = MultitouchInputMode.TOUCH_POINT;
    }

**Comment by KakashiSensei** [comment]
FPS drops when I place textField inside other sprites and as I increase the number of textfield fps drops faster. Having complex view without textfield, I was able to get 60fps.

Can you keep this feature of having BitmapFont in framework on priority. Thanks

**Comment by bp74** [comment]
The line with the MultitouchInputMode just enables or disables Touch events, it shouldn't affect the flickering at all - very strange. Sure i will take a look at the BitmapFonts soon - it will be an extension library for StageXL, maybe something like StageXL_BitmapFont

**Comment by KakashiSensei** [comment]
It flickers when I tap on the screen. Flickering was not occurring because of the updation of textfield (It does decreases the frame rate). I have made a simple view only with bitmaps and when I tap on the screen it flickers.

**Comment by bp74** [comment]
That's bad because this would mean the flickering would also happen with BitmapFont support :(

**Comment by KakashiSensei** [comment]
Flickering occurs only inside the webView not even in iOS browser.

BitmapFont will increase the fps overall.

**Comment by bp74** [comment]
You could try one more thing. Use Texture0 instead of Texture3, but this would be a ridiculous restriction of the WebView.

**Comment by KakashiSensei** [comment]
With changing to Texture0 now my fps is increased to 45 from 30 (using Texture3). What do you mean by ridiculous restriction of the WebView?

But not a replacement for bitmapTextView which could give 55-60 fps.

**Comment by bp74** [comment]
The WebGL standard specifies 32 texture units. The iPhone only supports 8 texture units. In our first attempt to fix the problem we changed the code from texture unit 10 to texture unit 3 (to use one of the 8 texture units on the iPhone). 

The idea was that the flickering (inside of the WebView) may go away if we don't use texture unit 3 but only texture unit 0 (which is the texture unit we use to render textures to the screen).

However, the StageXL version you have patched to do the tests with texture unit 3 is not really prepared to use texture unit 0 for the texture updates inside of the TextField class. I have changed the latest version of StageXL (which is not released and not stable) quite a bit to support those use cases and this new version will also have a better support for HiDpi textures. To make a long story short you could try to change the StageXL reference inside of your pubspec.yaml file to use the bleeding edge source from GitHub - but as i said earlier this version is not stable right now.

The URL for the StageXL GitHub repository is this:
https://github.com/bp74/StageXL.git

**Comment by bp74** [comment]
An early version of the BitmapFont library is available here:
https://github.com/bp74/StageXL_BitmapFont

Sample:
http://www.stagexl.org/show/bitmapfont/simple/example.html

It uses the head revision of the StageXL repository in case you wonder.

**Comment by KakashiSensei** [comment]
Nice I have tried it. It runs good. Waiting for all the features of textfield to be included in this library.

**Comment by bp74** [comment]
I don't think that it will provide all the features. It should be a light weight display object. The TextField class is everything else than light weight :)

**Comment by bp74** [comment]
What are your favorite features you want to have in BitmapText?

**Comment by KakashiSensei** [comment]
Might be same constructor as that of textfield and I can replace TextField class with BitmapTextField in Lib.dart file and done all textfield are replaced with bitmapTextField.

**Comment by KakashiSensei** [comment]
I found this BitmapTextField library in easeljs 
https://github.com/vikramarka/createjsbitmaptext

**Comment by bp74** [comment]
We have release a version 0.1.0 to Pub with the basic features.
Over the next days i will work on additional features.
I will open an issue in the StageXL_BitmapFont repository.
